/**
 * 12 · QR Portfolio — light page with 2 QR cards and 3 info chips below.
 * QR PNG buffers are pre-generated by the API route and passed as props,
 * so the block stays sync.
 */
import { View, Text, Image, StyleSheet } from '@react-pdf/renderer';
import { PrintPage } from '../ui/Page';
import { Eyebrow, TitleH1 } from '../ui/Typography';
import { LeadBox, BigBadge } from '../ui/Cards';
import { IconDiamond } from '../ui/Icons';
import { palette, fs, ls, lh } from '../tokens';
import { FONT_FAMILY, FONT_DISPLAY, FONT_MONO } from '../fonts';
import type { Content } from '../content/types';
import type { PortfolioData } from '../data/getPortfolioData';

type Props = {
  pageNum: number;
  content: Content['qr'];
  data: PortfolioData;
  qrBuffers: Buffer[];       // [projects QR, design QR]
};

const s = StyleSheet.create({
  titleRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: '8mm' },

  qrGrid: { flexDirection: 'row', gap: '6mm', marginTop: '2mm', marginBottom: '5mm' },
  qrCard: {
    flex: 1,
    backgroundColor: palette.creamCard,
    borderWidth: 0.3,
    borderColor: palette.lineCreamOnCream,
    borderTopWidth: 1.4,
    borderRadius: 2,
    padding: '5mm',
    flexDirection: 'column',
    gap: '3mm',
  },
  qrCardGold: { borderTopColor: palette.gold },
  qrCardTeal: { borderTopColor: palette.teal },
  qrHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: '3mm' },
  qrNum: { fontFamily: FONT_DISPLAY, fontWeight: 800, fontSize: fs.h3 + 2, color: palette.gold, lineHeight: 1 },
  qrTitle: { fontFamily: FONT_DISPLAY, fontWeight: 700, fontSize: fs.h2, color: palette.ink, lineHeight: lh.tight },
  qrCount: { flexDirection: 'row', alignItems: 'baseline', gap: '3mm', marginTop: '1mm' },
  qrCountNum: { fontFamily: FONT_DISPLAY, fontWeight: 800, fontSize: 32, lineHeight: 1, fontVariant: ['tabular-nums'] },
  qrCountNumGold: { color: palette.gold },
  qrCountNumTeal: { color: palette.teal },
  qrCountLabel: {
    fontFamily: FONT_FAMILY,
    fontSize: fs.eyebrow,
    fontWeight: 600,
    letterSpacing: ls.label,
    color: palette.muted,
    textTransform: 'uppercase',
    lineHeight: lh.normal,
  },
  qrImageWrap: { alignItems: 'center', marginTop: '2mm', marginBottom: '1mm' },
  qrImage: { width: '34mm', height: '34mm' },
  qrUrl: {
    textAlign: 'center',
    fontFamily: FONT_FAMILY,
    fontSize: fs.label,
    fontWeight: 600,
    letterSpacing: 0.02,
    color: palette.ink,
    paddingTop: '2mm',
    borderTopWidth: 0.2,
    borderTopColor: palette.lineCreamOnCream,
    borderTopStyle: 'dashed',
  },
  qrHint: { textAlign: 'center', fontFamily: FONT_FAMILY, fontSize: fs.small, color: palette.muted, marginTop: '1mm' },

  // Info chips
  infoLabel: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: '3mm',
    marginBottom: '3mm',
  },
  infoLine: { width: '12mm', height: 0.4, backgroundColor: palette.gold },
  infoLabelText: {
    fontFamily: FONT_FAMILY,
    fontSize: fs.eyebrow,
    fontWeight: 600,
    letterSpacing: ls.badge,
    color: palette.goldDark,
    textTransform: 'uppercase',
  },
  infoRow: { flexDirection: 'row', gap: '4mm' },
  infoChip: {
    flex: 1,
    padding: '3mm',
    backgroundColor: palette.creamCard,
    borderLeftWidth: 0.6,
    borderLeftColor: palette.gold,
    borderRadius: 1,
  },
  infoChipTitle: { flexDirection: 'row', alignItems: 'center', gap: '2mm', marginBottom: '1mm' },
  infoChipDot: { width: 6, height: 6, alignItems: 'center', justifyContent: 'center' },
  infoChipTitleText: { fontFamily: FONT_FAMILY, fontSize: fs.bodyLg, fontWeight: 700, color: palette.ink },
  infoChipDesc: { fontFamily: FONT_FAMILY, fontSize: fs.body, color: palette.muted, lineHeight: lh.normal },
});

export function QR({ pageNum, content, data, qrBuffers }: Props) {
  const counts = [data.countSmr, data.countPd];

  return (
    <PrintPage variant="light" pageNum={pageNum}>
      <Eyebrow>{content.eyebrow}</Eyebrow>
      <View style={s.titleRow}>
        <TitleH1 accent={content.accent} accentFirst>{content.title}</TitleH1>
        <BigBadge num={data.countRegistry} label="ЗАПИСЕЙ\nВ РЕЕСТРЕ" />
      </View>

      <LeadBox>{content.lead}</LeadBox>

      <View style={s.qrGrid}>
        {content.cards.map((card, i) => {
          const isGold = card.variant === 'gold';
          return (
            <View key={card.num} style={isGold ? [s.qrCard, s.qrCardGold] : [s.qrCard, s.qrCardTeal]}>
              <View style={s.qrHeader}>
                <Text style={s.qrNum}>{card.num}</Text>
                <Text style={s.qrTitle}>{card.title}</Text>
              </View>
              <View style={s.qrCount}>
                <Text style={isGold ? [s.qrCountNum, s.qrCountNumGold] : [s.qrCountNum, s.qrCountNumTeal]}>{counts[i]}</Text>
                <Text style={s.qrCountLabel}>{card.countLabel}</Text>
              </View>
              <View style={s.qrImageWrap}>
                <Image src={qrBuffers[i]} style={s.qrImage} />
              </View>
              <Text style={s.qrUrl}>{card.url}</Text>
              <Text style={s.qrHint}>{card.hint}</Text>
            </View>
          );
        })}
      </View>

      <View style={s.infoLabel}>
        <View style={s.infoLine} />
        <Text style={s.infoLabelText}>{content.infoLabel}</Text>
      </View>

      <View style={s.infoRow}>
        {content.info.map((it) => (
          <View key={it.title} style={s.infoChip}>
            <View style={s.infoChipTitle}>
              <IconDiamond size={7} color={palette.gold} />
              <Text style={s.infoChipTitleText}>{it.title}</Text>
            </View>
            <Text style={s.infoChipDesc}>{it.desc}</Text>
          </View>
        ))}
      </View>
    </PrintPage>
  );
}
